### ISSUE TITLE
As a developer, I want all my test are passing so that I have a high confidence in the product.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#234]
See CustomerRepositoryTest.whenFindByNameThenReturnCustomer test as it is failing.

**Comment by AmanAb428** [comment]
Hi @pouncilt 

Please review below PR and merge it.
 - https://github.com/byte-pushers/chucks-pick3/pull/238/files

**Comment by pouncilt** [comment]
done.
