### ISSUE TITLE
As a developer, I want to user implement logging so that I can debug application easier.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#235]
Either use regular logging or maybe AWS logging api.  Are there any cost affiliations with using AWS API for logging?

**Comment by AmanAb428** [comment]
@pouncilt 

Just to confirm here, as we are thinking about working with serverless lambda based mechanism for all projects then I should suggest to stay with AWS CloudWatch.

Most probably, I made this logging working with valid libraries which was conflicting each other earlier. However, we have some system out logs in lambdas which will move with AWS logging mechanism.

Additionally, we will try to configure the logging to store only few days of log in AWS. Please refer the Pricing page of AWS CloudWatch.

Link: https://aws.amazon.com/cloudwatch/pricing/

**Comment by AmanAb428** [comment]
Done and accepted
