### ISSUE TITLE
As a developer, I want URL endpoints to stay consistent from on deployment to the next so that the endpoints become stable.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#237]
Research how to register a domain name for AWS website, lambdas, and database.

**Comment by AmanAb428** [comment]
Hi @pouncilt 

Can you please suggest the appropriate domain name to move forward?

**Comment by pouncilt** [comment]
@AmanAb428 The domain name has been moved to AWS now.  We can continue this User Story now.  Let me know if you have any questions.

**Comment by pouncilt** [comment]
I need to create a certificate; but AWS is throwing error.  Search for: ACM on AWS Console.

**Comment by pouncilt** [comment]
Blocked by AWS certificate request is failing.
