### ISSUE TITLE
As a user I want to see a user friendly message explaining why the winning number is not available after the count down reaches zero so that I know to keep checking back for results.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#342]
Ensure the following exist:
- Ensure the user can manually retry and download the winning number.
- Ensure the user is displayed a user friendly error message, if count down reaches zero and no winning number available.
- Ensure the app can automatically retry to download the winning number, the next time the user select the draw time card.
- Ensure the app can automatically retry to download the winning number, even if the user never leaves the selected draw time card.

**Comment by ocampd1** [comment]
Ready to close pending PR
