### ISSUE TITLE
Optimization Effort: As a user I would like to see a quicker API start up time so that I have a better user experience.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#354]
Implement the following optimizations in the following sections of below link:
 - Asynchronous initialization
 - Custom @ControllerAdvice classes
 - Optimizing cold start times
   -- Static handlers
   -- Avoid component scan
   -- Avoid relationship autowiring
   -- Avoiding Constructor Injection by Name

https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot2

**Comment by AmanAb428** [comment]
@pouncilt 

We have already configured the below points earlier.
- Asynchronous initialization
- Optimizing cold start times

> Static handlers >> We have tried this option but it doesn't works for us as our application is not getting up within 10 seconds where AWS lambda is expecting to get started the application in 10 seconds. Spring Application is require more memory to get started the application context. Large amount of memory will cause an heavy invoice on AWS. Please refer below link for our reference on AWS Lambda Pricing. In my local, with 16 GB RAM is getting started within 5 seconds. However, On AWS with 1.5 GB RAM it is atleast getting started within 20 seconds approx. https://aws.amazon.com/lambda/pricing/

> Avoid component scan --> We have't used this annotation in our application at any point.

> Avoid relationship autowiring --> Applied the changes and deployed the jar to test it on server. But not having any luck on optimization.

>  Avoiding Constructor Injection by Name --> Applied the changes and deployed the jar to test it on server. But not having any luck on optimization.
