### ISSUE TITLE
Documentation Effort - How do we register domain names and SSL certificates.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#356]

**Comment by AmanAb428** [comment]
- To register a domain, we have followed the mentioned steps from the AWS documentation reference. Please find below link.

**AWS Documentation**: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register.html

- Once domain is getting registered, Route 53 will have to configure the DNS entry for the Domain. We have followed the below documentation to achieve this step.

**AWS Documentation**: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-name-servers-glue-records.html

For SSL certificate, There is a separate service in AWS called **Certificate Manager** where we have requested the SSL certificate for the respective domain. We have requested the Wildcard certificate.
