### ISSUE TITLE
As a user I want to see which host my enviroment is running from

### ISSUE THREAD

**Issue by ocampd1** [byte-pushers/chucks-pick3#415]
Create a variable which checks for host 

- Alter one for production
- Alter one for development
https://stackoverflow.com/questions/57969222/how-to-read-port-and-host-from-environment-ts-variable-for-angular-json-configur

https://www.jvandemo.com/how-to-use-environment-variables-to-configure-your-angular-application-without-a-rebuild/

**Comment by ocampd1** [comment]
Ready to close pending PR Approval.

**Comment by pouncilt** [comment]
Which PR has this feature?
