### ISSUE TITLE
BUG: As a user I wish to retrieve the winning numbers

### ISSUE THREAD

**Issue by ocampd1** [byte-pushers/chucks-pick3#426]
- Web scraper can no longer retrieve winning numbers, must be looked at in order to find cause.

**Comment by pouncilt** [comment]
JQuery is the cause of this bug as we are adding functions to the JS Object and JQuery does not handle this correctly.  We need to submit a but to JQuery and possible a PR fix.

**Comment by pouncilt** [comment]
Done.  Found issues with For in Loop via JQuery.  Implemented best practices in JQuery code for in loops.  Need to create a PR in JQuery.
