### ISSUE TITLE
When looking back at historical data, we should not show a drawing for a particular day, if there was not a drawing for that day.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#538]
Show general message when state lottery is closed on a particular day.
- Show general message.
- Don't show Internal Error pop up modal.
- Short Circuit down stream logic.
- State Lottery configuration that declare the draw days and draw times.

**Comment by ocampd1** [comment]
Complete pending PR: 
https://github.com/byte-pushers/chucks-pick3/pull/608
